### ISSUE TITLE
[CachyOS] Kernel version not matching what Tracee expects

### ISSUE THREAD

**Issue by therealOri** [dreadnode/dyana#25]
# Context
This is a [log.txt](https://github.com/user-attachments/files/18466100/log.txt) file from my terminal when I run the following command.
`dyana trace --loader pip --package psutil` | or loader python script.py
__ __
> Created a new issue as per request by: @GangGreenTemperTatum in [#22](https://github.com/dreadnode/dyana/issues/22#issuecomment-2599868949)

<br>

# Request
> Can you share the profiling command you are using please? if you can also confirm what python version and environment you are using would be great (project requires Python 3.10+ with PIP.)

I am unsure what you mean by "profiling command", but If you are referring to the command I use to get info about my system, it's called "fastfetch". A replacement for "Neofetch". My kernel version is `6.12.9-3 - (stable)` according to my kernel manager.

My global system python3 version is python 3.13+ and pip: `pip 24.3.1 from /usr/lib/python3.13/site-packages/pip (python 3.13)
`.
I am using `pyenv` for version control, etc. and for `dyana` I am using a `pyenv virtualenv` environment with `3.12.8`.

**Comment by therealOri** [comment]
> as a quick fix, you could try override the default events that Dyana will trace by passing a [custom policy](https://aquasecurity.github.io/tracee/v0.14/docs/policies/) to the tracer with: (ie one of the defaults do not look to be compatible with your host kernel)
>
> `dyana trace --loader automodel ... --policy examples/network_only_policy.yml`

I don't really understand how to make my own custom policy yet, so using the default example policy provided in custom policy link over at trace gives the following error:
```bash
👁‍🗨  tracer: using custom policy network_only_policy.yml
❌ error: v1beta1.PolicyFile.Validate: policy name  is invalid: [a lowercase RFC 1123 subdomain must consist of lower case 
alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for 
validation is '([-a-z0-9]*)?(\.([-a-z0-9]*)?)*')]
```

Sample Policy:
```yml
name: test policy
description: sample test policy
scope:
  - global
defaultAction: log
rules:
  - event: dropped_executable
  - event: security_file_open
    filter:
        - args.pathname=/tmp/*
  - event: sched_process_exec
    filter: 
        - uid=0
  - event: close
    filter:
        - retval!=0
```
